export { CartIcon } from './CartIcon'
export { ChevronIcon } from './ChevronIcon'
export { DiscordIcon } from './DiscordIcon'
export { GamepadIcon } from './GamepadIcon'
export { GiftIcon } from './GiftIcon'
export { MailIcon } from './MailIcon'
export { SparkIcon } from './SparkIcon'
export { SearchIcon } from './SearchIcon'
export { TelegramIcon } from './TelegramIcon'
export { UserIcon } from './UserIcon'
export type { IconProps } from './types'
