# Generated by Django 6.1 on 2026-08-18 12:07

from django.db import migrations


def create_categories(apps, schema_editor):
    Category = apps.get_model('shop', 'Category')
    
    # Top-level categories
    games = Category.objects.create(name='Games', slug='games')
    digital_products = Category.objects.create(name='Digital Products', slug='digital-products')
    accounts = Category.objects.create(name='Accounts', slug='accounts')
    
    # Games subcategories (parent: Games)
    Category.objects.create(name='Midnight', slug='midnight', parent=games)
    Category.objects.create(name='Wuthering Waves', slug='wuthering-waves', parent=games)
    Category.objects.create(name='Pandaria', slug='pandaria', parent=games)
    
    # Accounts > AI subcategory
    ai_accounts = Category.objects.create(name='AI', slug='ai', parent=accounts)
    
    # AI subcategories (parent: AI)
    Category.objects.create(name='Gemini', slug='gemini', parent=ai_accounts)
    Category.objects.create(name='Copilot', slug='copilot', parent=ai_accounts)
    Category.objects.create(name='ChatGPT', slug='chatgpt', parent=ai_accounts)
    Category.objects.create(name='Grok', slug='grok', parent=ai_accounts)
    Category.objects.create(name='Claude', slug='claude', parent=ai_accounts)
    Category.objects.create(name='DeepSeek', slug='deepseek', parent=ai_accounts)
    
    # Accounts > Social Media
    Category.objects.create(name='Social Media', slug='social-media', parent=accounts)
    
    # Accounts > Gift Cards
    gift_cards = Category.objects.create(name='Gift Cards', slug='gift-cards', parent=accounts)
    
    # Gift Cards subcategories
    Category.objects.create(name='Google Play', slug='google-play', parent=gift_cards)
    Category.objects.create(name='App Store', slug='app-store', parent=gift_cards)
    Category.objects.create(name='PlayStation', slug='playstation', parent=gift_cards)
    Category.objects.create(name='Xbox', slug='xbox', parent=gift_cards)


def remove_categories(apps, schema_editor):
    Category = apps.get_model('shop', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories, remove_categories),
    ]
