import Link from 'next/link'
import type { CSSProperties } from 'react'
import type { KeyProduct, Product, ProductDetail } from '@/types'
import { ROUTES } from '@/constants/routes'
import { Badge } from '@/components/Shared/Badge'
import { ProductArt } from '@/components/Shared/ProductArt'
import { AddToCartButton } from './AddToCartButton'

export type ProductCardProps = { product: Product | ProductDetail | KeyProduct; showNew?: boolean; variant?: 'standard' | 'featured'; className?: string }

export function ProductCard({ product, showNew = false, variant = 'standard', className = '' }: ProductCardProps) {
  if (variant === 'featured') {
    const featured = product as KeyProduct
    return <Link href={ROUTES.PRODUCT(featured.id)} className="group relative flex shrink-0 basis-[250px] snap-start flex-col overflow-hidden rounded-brand border border-line bg-surface p-[18px] shadow-[0_1px_2px_rgba(0,0,0,.04)] transition-[transform,border-color,box-shadow] duration-[280ms] ease-[cubic-bezier(.2,.8,.2,1)] hover:-translate-y-1.5 hover:scale-[1.03] hover:border-black/12 hover:shadow-[0_24px_46px_-16px_rgba(0,0,0,.24)] motion-reduce:transition-none max-[768px]:basis-[72vw] max-[480px]:basis-[78vw]" id={featured.id} style={{ '--art1': featured.art1, '--art2': featured.art2 } as CSSProperties}><span className="absolute start-3.5 top-3.5 z-[1] rounded-full border border-line bg-white/[.85] px-[9px] py-1 text-[10.5px] font-bold tracking-[.03em] text-muted backdrop-blur-[6px] dark:bg-[#141418]/[.85]">{featured.tag}</span><ProductArt art={featured.art} art1={featured.art1} art2={featured.art2} className="mb-3.5 h-[108px] rounded-[14px] text-[34px] font-extrabold" /><h3 className="m-0 mb-1 text-[15.5px] font-bold text-text">{featured.title}</h3><p className="m-0 mb-3.5 text-[12.5px] text-muted">{featured.description}</p><div className="flex items-center justify-between"><span className="text-[15px] font-bold text-text">{featured.price}<small className="me-[3px] text-[11.5px] font-medium text-muted">هزار تومان</small></span><span className="flex h-[34px] w-[34px] items-center justify-center rounded-[9px] border border-[#90CAF9] bg-[#E3F2FD] text-[17px] text-gold transition-[background,transform,color] duration-200 group-hover:scale-[1.12] group-hover:bg-[#E3F2FD] group-hover:text-[#0D47A1] dark:bg-[#90CAF9]/[.12] dark:text-[#90CAF9] dark:group-hover:bg-[#0D47A1] dark:group-hover:text-white">＋</span></div></Link>
  }
  const standard = product as Product | ProductDetail
  const statusLabel = standard.status === 'in_stock' ? 'موجود' : standard.status === 'out_of_stock' ? 'ناموجود' : 'به‌زودی'
  return <article className={`group rounded-2xl border border-line bg-surface p-4 shadow-[0_1px_2px_rgba(0,0,0,.03)] transition-[transform,border-color,box-shadow] duration-200 hover:-translate-y-1 hover:scale-[1.02] hover:border-black/12 hover:shadow-[0_20px_38px_-14px_rgba(0,0,0,.22)] motion-reduce:transition-none ${standard.status === 'out_of_stock' ? 'opacity-[.68] grayscale-[.45]' : ''} ${standard.status === 'coming_soon' ? 'border-dashed [&_.product-art]:saturate-[.7]' : ''} ${className}`} id={standard.id}><Link href={ROUTES.PRODUCT(standard.id)} className="block text-inherit no-underline">{showNew && <Badge tone="new" className="relative mb-2.5 inline-block text-[10px] font-bold">جدید</Badge>}<ProductArt art={standard.art} art1={standard.art1} art2={standard.art2} className="product-art mb-3 h-24 rounded-xl text-[26px] font-extrabold" /><h3 className="m-0 mb-[3px] text-[14.5px] font-bold text-text">{standard.title}</h3><p className="m-0 mb-3 text-[12px] text-muted">{standard.displayCategory}</p><div className="flex items-center justify-between"><span className="text-[14px] font-bold text-text">{standard.price}</span><Badge tone="stock" className={`flex items-center gap-[5px] text-[11px] ${standard.status !== 'in_stock' ? 'is-unavailable' : ''}`}><span className="h-[5px] w-[5px] rounded-full bg-teal" aria-hidden="true" />{statusLabel}</Badge></div></Link><div className="mt-3.5"><AddToCartButton productId={standard.id} status={standard.status} compact /></div></article>
}
